config/routes.rb
Rails.application.routes.draw do

  resources :candidatos
  # index
  root 'pages#index', as: 'home'

  # páginas 
  get 'empresa' => 'pages#empresa'
  get 'noticias' => 'pages#noticias'
  get 'contactos' => 'pages#contactos'
  get 'sobre-nos' => 'pages#sobre_nos'
  # serviços
  get 'servicos/formacao' => 'servicos#formacao'
  get 'servicos/consultoria' => 'servicos#consultoria'
  get 'servicos/gestao-de-projectos' => 'servicos#gestao_de_emprendimentos_pedagogicos'
  get 'junte-se-a-pluralia' => 'candidatos#new'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidato.rb
class Candidato < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :set_candidato, only: [:show, :edit, :update, :destroy]

  # GET /candidatos
  # GET /candidatos.json
  def index
    @candidatos = Candidato.all
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
  end

  # GET /candidatos/new
  def new
    @candidato = Candidato.new
  end

  # GET /candidatos/1/edit
  def edit
  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    @candidato = Candidato.new(candidato_params)

    respond_to do |format|
      if @candidato.save
        format.html { redirect_to new_candidato_path, notice: 'Candidatura feita com sucesso.' }
        format.json { render :show, status: :created, location: @candidato }
      else
        format.html { render :new }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatos/1
  # PATCH/PUT /candidatos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to @candidato, notice: 'Candidato was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidato }
      else
        format.html { render :edit }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    @candidato.destroy
    respond_to do |format|
      format.html { redirect_to candidatos_url, notice: 'Candidato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidato_params
      params.require(:candidato).permit(:nome, :email, :contacto, :morada, :cv_file_name, :mensagem)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
        @page_title = 'Plurália'
    end
    
    def empresa
        
    end

    def noticias
        
    end
    
    def junte_se_a_pluralia

    end
    
    def contactos
        
    end

    def sobre_nos
        
    end
    
    
end

app/controllers/servicos_controller.rb
class ServicosController < ApplicationController
    def formacao
        
    end

    def consultoria
        
    end
    
    def gestao_de_emprendimentos_pedagogicos
        
    end
end

app/helpers/admin_pages_helper.rb
module AdminPagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/candidatos/_form.html.erb
<style>
  label {
    margin-top: 10px;
  }
  input[type=submit] {
    margin-top: 10px;
    margin-bottom: 20px;
  }
</style>
<%= form_with(model: candidato, local: true, html: { multipart: true }) do |form| %>
  <% if candidato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidato.errors.count, "error") %> prohibited this candidato from being saved:</h2>

      <ul>
      <% candidato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, {class:'form-control'}%>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, {class:'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :contacto %>
    <%= form.text_field :contacto, {class:'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :morada %>
    <%= form.text_field :morada, {class:'form-control'} %>
  </div>

  <div class="field">
    <%= form.label :cv_file_name, 'CV'%>
    <%= form.file_field :cv_file_name, {class:'form-control-file'}%>
  </div>

  <div class="field">
    <%= form.label :mensagem %>
    <%= form.text_area :mensagem, {class:'form-control'} %>
  </div>

  <div class="actions">
    <%= form.submit({value:'Submter Candidatura', class:'btn btn-success'})%>
  </div>
<% end %>

app/views/candidatos/edit.html.erb
<h1>Editing Candidato</h1>

<%= render 'form', candidato: @candidato %>

<%= link_to 'Show', @candidato %> |
<%= link_to 'Back', candidatos_path %>

app/views/candidatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Contacto</th>
      <th>Morada</th>
      <th>Cv</th>
      <th>Mensagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidatos.each do |candidato| %>
      <tr>
        <td><%= candidato.nome %></td>
        <td><%= candidato.email %></td>
        <td><%= candidato.contacto %></td>
        <td><%= candidato.morada %></td>
        <td><%= candidato.cv_file_name %></td>
        <td><%= candidato.mensagem %></td>
        <td><%= link_to 'Show', candidato %></td>
        <td><%= link_to 'Edit', edit_candidato_path(candidato) %></td>
        <td><%= link_to 'Destroy', candidato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidato', new_candidato_path %>

app/views/candidatos/new.html.erb
<!-- START SECTION -->
<div class="section hero text-center background-dark dark-bg">
  <div class="background-image" style="background: url('/assets/img_bg_1.jpg') no-repeat center center; background-size: cover; opacity: .5;"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2 class="wow pulse" data-wow-iteration="infinite" data-wow-duration="1500ms">Candidaturas</h2>
      </div>
    </div>
  </div>
</div>
<!--.section -->
<div class="section">
  <div class='container'>
    <p id="notice"><%# notice %></p>
    <h3 class="section-title text-center">Junte-se à Plurália</h3>

    <%= render 'form', candidato: @candidato %>
  </div>
</div>

app/views/candidatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @candidato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @candidato.email %>
</p>

<p>
  <strong>Contacto:</strong>
  <%= @candidato.contacto %>
</p>

<p>
  <strong>Morada:</strong>
  <%= @candidato.morada %>
</p>

<p>
  <strong>Cv:</strong>
  <%= @candidato.cv_file_name %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @candidato.mensagem %>
</p>

<%= link_to 'Edit', edit_candidato_path(@candidato) %> |
<%= link_to 'Back', candidatos_path %>

app/views/commons/_footer.html.erb
        <!-- START SECTION -->
        <div id='footer' class="section background-dark dark-bg">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <h3 id='texto-sobre-nos' class="text-uppercase font-size-md letter-spacing-md font-weight-lg ">Sobre Nós</h3>
                        <p style='background: #fff; padding: 6px;'><img src='http://pluralia.net/Content/app/images/logo.png' style='width:75%'></p>
                        <p>A Plurália é uma empresa privada de direito angolano que nasce da congregação de vontades entre um grupo de académicos e profissionais com vasta experiência internacional em formação, consultoria, gestão de projectos e negócios.</p>
                    </div>
                    <div class="col-md-4 col-md-offset-1">
                        <h3 class="text-uppercase font-size-md letter-spacing-md font-weight-lg ">Nosso Escritório</h3>
                        <address>
                            <strong>Endereço</strong><br>
                            Angola, Luanda, Talatona, Luanda Sul<br>
                            Edificio Banco Sol - Piso 1<br>
                        </address>
                        <address>
                            <strong>Telefone</strong><br>
                            <abbr title="Phone"><i class="fas fa-phone-square"></i></abbr> +244 933 911 070
                        </address>
                        <address>
                            <strong>E-mail</strong><br>
                            <a href="mailto:info@pluralia.net">info@pluralia.net</a>
                        </address>
                    </div>
                    <div class="col-md-4">
                        <h3 class="text-uppercase font-size-md letter-spacing-md font-weight-lg ">Nosso Escritório</h3>
                        <address>
                            <strong>Endereço</strong><br>
                            Angola, Luanda, Talatona, Luanda Sul<br>
                            Edificio Banco Sol - Piso 1<br>
                        </address>
                        <address>
                            <strong>Telefone</strong><br>
                            <abbr title="Phone"><i class="fas fa-phone-square"></i></abbr> +244 933 911 070
                        </address>
                        <address>
                            <strong>E-mail</strong><br>
                            <a href="mailto:info@pluralia.net">info@pluralia.net</a>
                        </address>
                    </div>
                    <div class="col-md-12 margin-top-md margin-bottom-md" style="opacity: .2;">
                        <hr/>
                    </div>
                    <div class="col-md-12 margin-top-md text-center font-size-sm text-upercase">
                        <p>© Copyright <%=Time.now.year %> <a href="/" title="Plurália"><strong>Plurália</strong></a> Todos os direitos reservados.</p>
                    </div>
                </div>
            </div>
        </div>
  		<!--/.section -->
  
  		<!-- jQuery -->
  		<script src="//code.jquery.com/jquery.js"></script>
  		<!-- Bootstrap JavaScript -->
  		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  	</body>
  </html>

app/views/commons/_navigation.html.erb
<nav id='menu' class="navbar navbar-default navbar-fixed-top" role="navigation" style='box-shadow: 2px 1px rgba(0,0,0,.1); '>
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand logo" href='/' alt='Logotipo - Plurália'></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Início</a></li>
                <li><a href="/sobre-nos">Sobre Nós</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Serviços <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="/servicos/formacao">Formação</a></li>
                        <li><a href="/servicos/consultoria">Consultoria</a></li>
                        <li><a href="/servicos/gestao-de-projectos">Gestão de Empreendimentos Pedagógicos</a></li>
                    </ul>
                </li>
                <li><a href="/#noticias">Notícias</a></li>
                <li><a href="/junte-se-a-pluralia">Junte-se à Plurália</a></li>
                <li><a href="/#contactos">Contactos</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>
<div id='after'></div>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html lang="">
  	<head>
  		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name="viewport" content="width=device-width, initial-scale=1">
  		<title><%= @page_title %></title>
  
  		<!-- Bootstrap CSS -->
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  		<!-- Google Fonts -->
  		<link href='https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700' rel='stylesheet' type='text/css'>
  		<!-- Font Awesome -->
  		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  		<!-- Style -->
  		<link href='/assets/style.css' rel='stylesheet' type='text/css'>

			<link href='/assets/animate.css' rel='stylesheet' type='text/css'>

			<link href='/assets/mystyle.css' rel='stylesheet' type='text/css'>
      <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  		<!--[if lt IE 9]>
  			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
  			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  		<![endif]-->
  </head>
  <body>
    <%= render "commons/navigation" %> 

    <%= yield %>

		<%= render "commons/footer" %>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<script src="/assets/wow.js"></script>
		<script>
			wow = new WOW(
      {
        animateClass: 'animated',
        offset:       100,
        callback:     function(box) {
          console.log("WOW: animating <" + box.tagName.toLowerCase() + ">")
        }
      }
    );
    wow.init();
		</script>
  </body>
</html>

app/views/pages/contactos.html.erb
<h1>Contactos</h1>

app/views/pages/index.html.erb
<!-- START SECTION -->
<div class="section hero text-center background-dark dark-bg">
<div class="background-image" style="background: url(assets/img_bg_3.jpg) no-repeat center center; background-size: cover; opacity: .4;"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Bem vindo a Plurália</h2>
            <!--<p class="lead">Formação, consultoria, gestão de projectos e negócios.</p>
            <ul class="list-inline">
                <li><a href="/servicos/formacao" title="Formação" class="btn btn-md btn-danger">Formação</a></li>
                <li><a href="/servicos/consultoria" title="Consultoria" class="btn btn-md btn-primary">Consultoria</a></li>
                <li><a href="/servicos/gestao-de-projectos" title="Gestão de Projectos" class="btn btn-md btn-info">Gestão de Projectos</a></li>               
            </ul>-->
            <p class='lead'>Laudantium ullam consequatur repellat debitis maxime.</p>
            <ul class="list-inline">
                <li><a href="/#servicos" title="Serviços" class="btn btn-md btn-info">Serviços</a></li>
                <li><a href="/sobre-nos" title="Sobre Nós" class="btn btn-md btn-success">Sobre Nós</a></li>
            </ul>
        </div>
    </div>
</div>
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section background-light" id='servicos'>
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="section-title">Nossos Serviços</h2>
            <p class="section-description">Laudantium ullam consequatur repellat debitis maxime.</p>
        </div>
        <div class="col-md-4">
            <div class="service-block text-center">
                <i class="fas fa-graduation-cap"></i>
                <h3>Formação</h3>
                <p>O intento de propiciar momentos formativos de carácter profissional...</p>
                <a href="/servicos/formacao" title="Saiba mais" class="btn btn-sm btn-primary">Saiba mais ></a>
            </div><!--/.service-block-->
        </div>
        <div class="col-md-4">
            <div class="service-block text-center">
                <i class="fas fa-briefcase"></i>
                <h3>Consultoria</h3>
                <p>Ajudamo-lo a desenvolver ideias, negócios e a implementar projectos...</p>
                <a href="/servicos/consultoria" title="Saiba mais" class="btn btn-sm btn-primary">Saiba mais ></a>
            </div><!--/.service-block-->
        </div>
        <div class="col-md-4">
            <div class="service-block text-center">
                <i class="fas fa-network-wired"></i>
                <h3>Gestão de Projectos</h3>
                <p>Apostamos na criação e dinamização de empreendimentos pedagógicos...</p>
                <a href="/servicos/gestao-de-projectos" title="Saiba mais" class="btn btn-sm btn-primary">Saiba mais ></a>
            </div><!--/.service-block-->
        </div>
    </div>
</div>
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section hero text-center background-primary dark-bg">
<div class="background-image" style="background: url(assets/hero.jpg) no-repeat fixed center center; background-size: cover; opacity: .2;"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase letter-spacing-md font-weight-lg margin-zero">A Nossa Meta é a Excelência!</h3>
        </div>
    </div>
</div>
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section" id="noticias">
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="section-title">Notícias Recentes</h2>
            <p class="section-description">Laudantium ullam consequatur repellat debitis maxime.</p>
        </div>
        <div class="col-md-4">
            <div class="entry">
                <div class="entry-media">
                    <a href="#" title="">
                        <span class="absolute-wrapper"></span>
                        <img src="assets/blog1.jpg" alt="" class="img-responsive" />
                    </a>
                </div>
                <h3 class="entry-title"><a href="#" title="Yelp Is Awful for Everyone Involved">Yelp Is Awful for Everyone Involved</a></h3>
                <p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est.</p>
                <a href="#" title="Learn More" class="btn read-more btn-sm btn-primary">Learn More</a>
            </div><!--/.entry-->
        </div>
        <div class="col-md-4">
            <div class="entry">
                <div class="entry-media">
                    <a href="#" title="">
                        <span class="absolute-wrapper"></span>
                        <img src="assets/blog2.jpg" alt="" class="img-responsive" />
                    </a>
                </div>
                <h3 class="entry-title"><a href="#" title="2 Best Sites to Build Your Own Website">2 Best Sites to Build Your Own Website</a></h3>
                <p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est.</p>
                <a href="#" title="Learn More" class="btn read-more btn-sm btn-primary">Learn More</a>
            </div><!--/.entry-->
        </div>
        <div class="col-md-4">
            <div class="entry">
                <div class="entry-media">
                    <a href="#" title="">
                        <span class="absolute-wrapper"></span>
                        <img src="assets/blog3.jpg" alt="" class="img-responsive" />
                    </a>
                </div>
                <h3 class="entry-title"><a href="#" title="2 Best Sites to Build Your Own Website">2 Best Sites to Build Your Own Website</a></h3>
                <p>Sed egestas, ante et vulputate volutpat, eros pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est.</p>
                <a href="#" title="Learn More" class="btn read-more btn-sm btn-primary">Learn More</a>
            </div><!--/.entry-->
        </div>
    </div><!--/.row-->
</div><!--/.container-->
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section hero text-center background-dark dark-bg">
<div class="background-image" style="background: url(assets/hero.jpg) no-repeat fixed center center; background-size: cover; opacity: .2;"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase letter-spacing-md font-weight-lg margin-zero">Marcamos presença no crescimento de Angola!</h3>
        </div>
    </div>
</div>
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section" id="contactos">
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h2 class="section-title">Contacte-nos</h2>
            <p class="section-description">Laudantium ullam consequatur repellat debitis maxime.</p>
        </div>
        <div class="col-md-8 col-md-offset-2">
            <form id="contact" method="post" class="form" role="form">
                <div class="row">
                    <div class="col-md-6 form-group">
                        <input class="form-control" id="name" name="nome" placeholder="Nome" type="text" required />
                    </div>
                    <div class="col-md-6 form-group">
                        <input class="form-control" id="email" name="email" placeholder="Email" type="email" required />
                    </div>
                </div>
                <textarea class="form-control" id="message" name="mensagem" placeholder="Mensagem" rows="5"></textarea>
                <br />
                <div class="row">
                    <div class="col-md-12 form-group">
                        <button class="btn btn-primary" type="submit">Enviar</button>
                    </div>
                </div>
            </form>
        </div>
    </div><!--/.row-->
</div><!--/.container-->
</div>
<!--/.section -->

<!-- START SECTION -->
<div class="section hero text-center background-light">
<div class="background-image" style="background: url(assets/hero.jpg) no-repeat fixed center center; background-size: cover; opacity: .2;"></div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase letter-spacing-md font-weight-lg margin-zero">Abraçamos os Maiores Desafios!</h3>
        </div>
    </div>
</div>
</div>
<!--/.section -->